In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("AWE_1000_score.csv")

In [ ]:
df.head(2)

Unnamed: 0                     id nationality sex          title  \
0           1  A100000_v01.txt_2.txt          중국  남자  우리 나라의 계절과 날씨   
1           2  A100000_v02.txt_1.txt          중국  여자         주말 이야기   

                                             content  score  
0  제 나라의 계절은 아주 좋아요. 네 계절이 있습니다. 봄에는 날씨가 좋아요. 꽃이 ...     80  
1  어제 명동에 갔습니다. 친구하고 같이 갔습니다. 가게가 많습니다. 옷가게가 있었습니...     70

In [ ]:
df["sentence"] = df["content"].apply(lambda x: len(x.split(".")))
#df["content"].apply(lambda x: len(x.split("."))).value_counts()

In [ ]:
import torch

In [ ]:
x_train = df["sentence"].to_numpy()
y_train = df["score"].to_numpy()

In [ ]:
x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)

In [ ]:
optimizer = torch.optim.SGD(params=[W], lr=0.1)

In [ ]:
# 데이터
#x_train = torch.FloatTensor([[1], [2], [3]]) 
#y_train = torch.FloatTensor([[1], [2], [3]]) # 모델 초기화
W = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W], lr=0.15)
nb_epochs = 10
for epoch in range(nb_epochs + 1):
# H(x) 계산
  hypothesis = x_train * W
  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)
  print('Epoch {:4d}/{} W: {:.3f} Cost: {:.6f}'.format( epoch, nb_epochs, W.item(), cost.item()
  ))
  # cost로 H(x) 개선 
  optimizer.zero_grad() 
  cost.backward() 
  optimizer.step()

Epoch    0/10 W: 0.000 Cost: 5608.200195
Epoch    1/10 W: 233.823 Cost: 6322896.000000
Epoch    2/10 W: -8105.219 Cost: 8041370624.000000
Epoch    3/10 W: 289297.594 Cost: 10227932987392.000000
Epoch    4/10 W: -10317248.000 Cost: 13009052212658176.000000
Epoch    5/10 W: 367953568.000 Cost: 16546398753796390912.000000
Epoch    6/10 W: -13122661376.000 Cost: 21045598030079411093504.000000
Epoch    7/10 W: 468005355520.000 Cost: 26768194840882427889451008.000000
Epoch    8/10 W: -16690897223680.000 Cost: 34046836186812315357893623808.000000
Epoch    9/10 W: 595262468784128.000 Cost: 43304636806515645697631302189056.000000
Epoch   10/10 W: -21229383394000896.000 Cost: 55079780058408038826072024817860608.000000


### 왜 loss가 발산할까?
 - lr이 너무 높아서
 - sample이 너무 많아서 loss값이 애초에 크다
 

In [ ]:
class MyLinearModel(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = torch.nn.Linear(in_features=2, out_features= 1)

  def forward(self, x):
    return self.linear(x)

In [ ]:
myLin = MyLinearModel()

In [ ]:
dummy_x_train = torch.FloatTensor([[2,5],[3,7],[4,9]])
dummy_y_train = torch.FloatTensor([[2],[3],[4]])

In [ ]:
list(myLin.parameters())

[Parameter containing:
 tensor([[0.7250, 0.0720]], requires_grad=True), Parameter containing:
 tensor([0.3461], requires_grad=True)]

In [ ]:
optimizer = torch.optim.SGD(myLin.parameters(), lr=0.01)

In [ ]:
myLin(dummy_x_train)

tensor([[-0.2273],
        [-0.3272],
        [-0.4271]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F

In [ ]:
nb_epochs = 10
for epoch in range(nb_epochs + 1):
# H(x) 계산
  hypothesis = myLin(x_train)
  # cost 계산
  cost = F.mse_loss(hypothesis, y_train)
  print('Epoch {:4d}/{} Cost: {:.6f}'.format( epoch, nb_epochs, cost.item()
  ))
  # cost로 H(x) 개선 
  optimizer.zero_grad() 
  cost.backward() 
  optimizer.step()

Epoch    0/10 W: 757122676094402560.000 Cost: 11.876952
Epoch    1/10 W: 757122676094402560.000 Cost: 0.726773
Epoch    2/10 W: 757122676094402560.000 Cost: 0.055365
Epoch    3/10 W: 757122676094402560.000 Cost: 0.014908
Epoch    4/10 W: 757122676094402560.000 Cost: 0.012442
Epoch    5/10 W: 757122676094402560.000 Cost: 0.012264
Epoch    6/10 W: 757122676094402560.000 Cost: 0.012224
Epoch    7/10 W: 757122676094402560.000 Cost: 0.012192
Epoch    8/10 W: 757122676094402560.000 Cost: 0.012161
Epoch    9/10 W: 757122676094402560.000 Cost: 0.012129
Epoch   10/10 W: 757122676094402560.000 Cost: 0.012098
